set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports bee]
set_property PACKAGE_PIN A18 [get_ports {seg_en_0[7]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en_0[6]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en_0[5]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en_0[4]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en_0[3]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en_0[2]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en_0[1]}]
set_property PACKAGE_PIN C19 [get_ports {seg_en_0[0]}]
set_property PACKAGE_PIN E13 [get_ports {seg_out_0[7]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out_0[6]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out_0[5]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out_0[4]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out_0[3]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out_0[2]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out_0[1]}]
set_property PACKAGE_PIN F15 [get_ports {seg_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports player1]
set_property IOSTANDARD LVCMOS33 [get_ports player2]
set_property IOSTANDARD LVCMOS33 [get_ports player3]
set_property IOSTANDARD LVCMOS33 [get_ports player4]
set_property IOSTANDARD LVCMOS33 [get_ports starttimer]
set_property IOSTANDARD LVCMOS33 [get_ports no]
set_property IOSTANDARD LVCMOS33 [get_ports yes]

set_property IOSTANDARD LVCMOS33 [get_ports set1]


set_property PACKAGE_PIN U5 [get_ports player1]
set_property PACKAGE_PIN T5 [get_ports player2]
set_property PACKAGE_PIN T4 [get_ports player3]
set_property PACKAGE_PIN R4 [get_ports player4]
set_property PACKAGE_PIN V9 [get_ports starttimer]
set_property PACKAGE_PIN R1 [get_ports no]
set_property PACKAGE_PIN P1 [get_ports yes]

set_property PACKAGE_PIN R6 [get_ports set1]


set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports startgame]
set_property PACKAGE_PIN W4 [get_ports startgame]
set_property PACKAGE_PIN A19 [get_ports bee]


set_property IOSTANDARD LVCMOS33 [get_ports jia1]
set_property IOSTANDARD LVCMOS33 [get_ports jia2]
set_property IOSTANDARD LVCMOS33 [get_ports jian1]
set_property IOSTANDARD LVCMOS33 [get_ports jian2]
set_property IOSTANDARD LVCMOS33 [get_ports time1]
set_property IOSTANDARD LVCMOS33 [get_ports time2]

set_property PACKAGE_PIN W9 [get_ports jia1]
set_property PACKAGE_PIN Y7 [get_ports jia2]
set_property PACKAGE_PIN Y8 [get_ports jian1]
set_property PACKAGE_PIN AB8 [get_ports jian2]
set_property PACKAGE_PIN AA8 [get_ports time1]
set_property PACKAGE_PIN V8 [get_ports time2]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]




